import Head from 'next/head'
import BarChart01 from '../components/BarChart01'
import BottomSection from '../components/BottomSection'
import BottomSectionPie from '../components/BottomSectionPie'
import BottomSectionPieGraph from '../components/BottomSectionPieGraph'
import Content1 from '../components/Content1'
import Content1_Data from '../components/Content1_Data'
import Header from '../components/Header'
import HeaderBottom from '../components/HeaderBottom'
import MiddleSection from '../components/MiddleSection'
import NavBar from '../components/NavBar'
import Widgets from '../components/Widgets'
import WidgetsOption from '../components/WidgetsOption'



export default function Home() {
  return (
    <div className="h-screen">
    <Head>
      <title>DashBoard</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <HeaderBottom />
    <main className="flex h-screen top-0 sticky">
      <div className="w-[10%] xl:w-[5%] ">
      <NavBar />
      </div>
      <div className="w-[90%] xl:w-[95%] overflow-scroll scrollbar-hide">
      <MiddleSection />
      </div>
    </main>
  
  </div>

 
  //     <Head>
  //       <title>Dashboard</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //   <Header />
  //   <HeaderBottom />
  //   <NavBar />
   
  //   <Content1_Data />
  
  //     <BarChart01 />
  //   <MiddleSection />
    
  // <BottomSection />
    
  //   <BottomSectionPieGraph />
  //   <Widgets />
   
  //   </div>
  )
}